# Generated by Django 3.1.7 on 2021-05-31 08:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
