# Generated by Django 3.1.7 on 2021-07-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210711_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
