# Generated by Django 3.1.7 on 2021-04-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210403_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='email_to',
            field=models.EmailField(max_length=50, verbose_name='Email подписчика'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='tbl_author',
        ),
    ]
