# Generated by Django 3.1.7 on 2021-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm', models.CharField(max_length=50, verbose_name='utm mark')),
                ('time_exec', models.CharField(max_length=20, verbose_name='time execution')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=200, verbose_name='path')),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
