# Generated by Django 3.1.7 on 2021-04-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210413_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
