# Generated by Django 3.1.7 on 2021-04-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210413_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_exec',
            field=models.CharField(max_length=20, verbose_name='Time execution'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user_ip',
            field=models.CharField(max_length=20, null=True, verbose_name='User IP'),
        ),
    ]
