# Generated by Django 3.1.7 on 2021-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210413_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user_ip',
            field=models.CharField(max_length=20, verbose_name='User IP'),
        ),
    ]
