# Generated by Django 3.1.7 on 2021-04-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_books_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
